services:
  mongodb:
    image: mongo:7-jammy
    hostname: mongodb
    restart: always
    command: ["mongod","--replSet", "rs0","--bind_ip_all"]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}
    ports:
      - 27017:27017
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot
    entrypoint:
    - bash
    - -c
    - |
      openssl rand -base64 756 > /data/configdb/keyfile
      chmod 400 /data/configdb/keyfile
      chown 999:999 /data/configdb/keyfile
      exec docker-entrypoint.sh mongod --replSet rs0 --bind_ip_all --keyFile /data/configdb/keyfile
    healthcheck:
      test: ["CMD", "mongosh", "-u", "${DB_ADMIN}", "-p", "${DB_PASS}", "--authenticationDatabase", "admin", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 10s
  mongo_init:
    image: mongo:7-jammy
    depends_on:
      mongodb:
       condition: service_healthy
    restart: "no"
    entrypoint:
      - mongosh
      - --host
      - mongodb:27017
      - -u
      - ${DB_ADMIN}
      - -p
      - ${DB_PASS}
      - --authenticationDatabase
      - admin
      - --eval
      - "try { rs.status() } catch (err) { rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'mongodb:27017'}]}) }"

  app:
    container_name: backend
    restart: always
    image: devsrecipe/tasktracker:backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4000
      - WEB_ORIGIN=${WEB_ORIGIN:-http://13.229.171.117}
      - MONGODB_URI=mongodb://${DB_ADMIN:-admin}:${DB_PASS:-admin}@mongodb:27017/task?authSource=admin&replicaSet=rs0&directConnection=true
      - DATABASE_URL=mongodb://${DB_ADMIN:-admin}:${DB_PASS:-admin}@mongodb:27017/task?authSource=admin&replicaSet=rs0&directConnection=true
    depends_on:
      mongodb:
        condition: service_healthy
      mongo_init:
        condition: service_completed_successfully

  web:
    container_name: web
    restart: always
    image: devsrecipe/tasktracker:web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=${API_URL:-http://13.229.171.117/api/v1}
    depends_on:
      mongodb:
        condition: service_healthy
      mongo_init:
        condition: service_completed_successfully
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - web
    restart: always

volumes:
  db:
  configdb:
  mongot:
