import { createCookie } from 'react-router';

/* ==========================================================================
   The reset challenge, browser side
   --------------------------------------------------------------------------
   A password reset has two moments — asking for it, and completing it — and
   the emailed token only proves something about the second. It proves you can
   read the mailbox. It proves nothing about who asked, and the two need not be
   the same person: mail is forwarded, shared, synced to a spare tablet, and
   left open on unlocked screens.

   So the API issues a second secret when a reset is requested, and requires it
   back on completion. This file is where that secret lives in between.

   **Why here and not in the API.** The API never speaks to a browser. Every
   request reaches it from this web server acting on the user's behalf, so a
   `Set-Cookie` written on an API response would be stored by this server
   rather than by the person sitting at the screen. The tier holding the
   browser's connection has to be the tier that sets the cookie.

   The secret is still generated by the API, still never appears in the email,
   and is still only ever held by the browser that asked. All that moved is
   which server writes the header.
   ========================================================================== */

try {
  if (!process.env.SESSION_SECRET) {
    process.loadEnvFile?.('.env');
  }
} catch {}

const SESSION_SECRET = process.env.SESSION_SECRET;

if (!SESSION_SECRET || SESSION_SECRET.length < 32) {
  throw new Error('SESSION_SECRET must be set and at least 32 characters.');
}

export const resetChallenge = createCookie('tf_reset_challenge', {
  // `httpOnly` so a script on the page cannot read it — the whole point is
  // that it is something only the browser possesses, not something the page
  // can hand over.
  httpOnly: true,

  // `lax`, not `strict`. The user arrives on the reset page by clicking a link
  // in their mail client, which is a cross-site navigation: `strict` would
  // withhold the cookie on precisely the request the feature depends on, and
  // every same-browser reset would fall through to the code.
  sameSite: 'lax',

  secure: process.env.NODE_ENV === 'production',
  path: '/',

  // An hour, matching the token it is paired with. A challenge outliving its
  // token is a key to a door that has been bricked up.
  maxAge: 60 * 60,

  // Signed, so a browser cannot substitute a value of its own choosing. It
  // would not help an attacker — the API compares against a stored hash — but
  // an unsigned cookie invites the attempt and muddies the logs.
  secrets: [SESSION_SECRET],
});

export async function readResetChallenge(request: Request): Promise<string | undefined> {
  const value: unknown = await resetChallenge.parse(request.headers.get('Cookie'));
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}
