services:
  mongodb:
    image: mongo:7
    container_name: taskforge-mongo
    ports: ['27017:27017']
    volumes:
      - taskforge-mongodata:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  taskforge-mongodata:
